app:
  name: vladexpert

#jwt:
#  header: Authorization
#  expires_in: 600 # 10 minutes
#  secret: queenvictoria
#  cookie: AUTH-TOKEN
#

spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/jwtspring
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#    initialize: true
